### ISSUE TITLE
Huge memory/cpu usage validating DTDs

### ISSUE THREAD

**Issue by orlitzky** [UweSchmidt/hxt#15]
I have an XML file of moderate size (around 31KiB), and a relatively small DTD: 
https://gist.github.com/mjorlitzky/8407085. Here's a short program to parse the XML:

```Haskell
module Main
where

import Text.XML.HXT.Core

opts = [ withRemoveWS yes,
         withValidate no ]

main :: IO ()
main = do
  foo <- runX $ readDocument opts "20118073.xml"
  putStrLn "Hello, world!"
```

When parsing *without* validation enabled, everything is fine. Here are the stats from GHC:

```
$ ./Main +RTS -s
Hello, world!
      71,581,608 bytes allocated in the heap
      18,919,928 bytes copied during GC
       4,953,112 bytes maximum residency (5 sample(s))
         652,600 bytes maximum slop
              11 MB total memory in use (0 MB lost due to fragmentation)

                                    Tot time (elapsed)  Avg pause  Max pause
  Gen  0       134 colls,     0 par    0.02s    0.02s     0.0001s    0.0005s
  Gen  1         5 colls,     0 par    0.02s    0.02s     0.0039s    0.0091s

  INIT    time    0.00s  (  0.00s elapsed)
  MUT     time    0.03s  (  0.03s elapsed)
  GC      time    0.04s  (  0.04s elapsed)
  EXIT    time    0.00s  (  0.00s elapsed)
  Total   time    0.07s  (  0.06s elapsed)

  %GC     time      57.6%  (58.9% elapsed)

  Alloc rate    2,790,593,579 bytes per MUT second

  Productivity  42.2% of total user, 43.0% of total elapsed
```

If, however, we remove he line disabling validation,

```patch
@@ -3,8 +3,7 @@
 
 import Text.XML.HXT.Core
 
-opts = [ withRemoveWS yes,
-         withValidate no ]
+opts = [ withRemoveWS yes ]
 
 main :: IO ()
 main = do
```

then resource usage goes through the roof. Here are the GHC statistics for the version that does validation:

```
$ ./Main +RTS -s
Hello, world!
  15,989,938,664 bytes allocated in the heap
   3,221,674,272 bytes copied during GC
     296,820,320 bytes maximum residency (17 sample(s))
      11,244,888 bytes maximum slop
             841 MB total memory in use (0 MB lost due to fragmentation)

                                    Tot time (elapsed)  Avg pause  Max pause
  Gen  0     30610 colls,     0 par    2.61s    2.61s     0.0001s    0.0004s
  Gen  1        17 colls,     0 par    1.94s    1.94s     0.1142s    0.4882s

  INIT    time    0.00s  (  0.00s elapsed)
  MUT     time    7.94s  (  7.95s elapsed)
  GC      time    4.55s  (  4.55s elapsed)
  EXIT    time    0.06s  (  0.06s elapsed)
  Total   time   12.54s  ( 12.56s elapsed)

  %GC     time      36.2%  (36.3% elapsed)

  Alloc rate    2,013,649,727 bytes per MUT second

  Productivity  63.8% of total user, 63.7% of total elapsed
```

Enabling profiling implicates some specific functions:

```
	Mon Jan 13 15:26 2014 Time and Allocation Profiling Report  (Final)

	   Main +RTS -p -RTS

	total time  =       68.95 secs   (68946 ticks @ 1000 us, 1 processor)
	total alloc = 19,888,508,112 bytes  (excludes profiling overheads)

COST CENTRE        MODULE                              %time %alloc

delta              Text.XML.HXT.DTDValidation.XmlRE     36.2   15.9
isElem             Text.XML.HXT.DOM.XmlNode             12.8    0.0
.                  Control.Arrow.ListArrow               9.9   29.7
nameOfElem         Text.XML.HXT.DTDValidation.TypeDefs   7.9   33.9
delta.expectedNode Text.XML.HXT.DTDValidation.XmlRE      5.4    0.0
qualifiedName      Text.XML.HXT.DOM.QualifiedName        5.1    0.0
getElemName        Text.XML.HXT.DOM.XmlNode              2.6    0.0
arr.\              Control.Arrow.ListArrow               2.5    0.0
arr                Control.Arrow.ListArrow               2.5   11.1
delta.allowed      Text.XML.HXT.DTDValidation.XmlRE      2.4    0.0
getElemName        Text.XML.HXT.Arrow.XmlArrow           2.3    0.0
re_seq             Text.XML.HXT.DTDValidation.RE         2.1    2.5
getNode            Data.Tree.NTree.TypeDefs              1.9    0.0
nullable           Text.XML.HXT.DTDValidation.RE         1.8    0.0
isElem             Text.XML.HXT.DOM.XmlNode              1.7    0.0
re_alt             Text.XML.HXT.DTDValidation.RE         0.9    2.0
getElemName        Text.XML.HXT.DOM.XmlNode              0.6    3.7
```

**Comment by svenpanne** [comment]
Validation is basically unusable for me, too, my use case is as follows: The OpenGL registry contains descriptions of various OpenGL-related APIs in XML. The schema for this XML is available as `registry.rnc` at the [Khronos SVN repository](https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/). To make it usable for hxt, one can convert it with [trang](https://code.google.com/p/jing-trang/) to the non-compact syntax (for a tiny problem with that, see #34). Reading the XML descriptions for the various APIs (e.g. gl.xml in the above SVN repository) without validation is fine, but adding `withRelaxNG "registry.rng"` totally blows away the memory: Even for the smaller API descriptions (roughly 100kB) I had to kill my program after it allocated more than 22GB during the validation step.

**Comment by UweSchmidt** [comment]
please can you send me your modified schema file `registry.rng`. My download of the trang archive does not contain any `Main` class or at least I didn't find it.

**Comment by svenpanne** [comment]
I uploaded it to https://gist.github.com/svenpanne/1305acbc280bccf644fe. Just for reference: I used the trang package from Ubuntu 14.04, it works out of the box, giving you a `trang` command.

**Comment by UweSchmidt** [comment]
Thanks for the gist. It showed up, that in the validation process the algorithm checking the content model of an element used an exponentially growing intermediate structure, a kind of regexp. By transforming this structure a bit more clever this growth is eliminated. The latest version `hxt-relaxng-9.1.5.3` on hackage validates the OpenGL documents in an acceptable time. Hope, it will do that on your machine too. If there's some spare time, I'll have a look into the DTD validation, could be that there's a similar error.

**Comment by svenpanne** [comment]
Works perfectly for me, thanks. I think issue can be closed.

**Comment by UweSchmidt** [comment]
A similar error as with RelaxNG validation was in the DTD validation module. There the same strategy with validation of the content model by derivation of regular expressions is used. But the set of opertors in DTD differs from RelaxNG. In the test suite in `http://michael.orlitzky.com/git/htsn-import.git` there are some DTDs, which contain ambiguous grammars, e.g. `Odds_XML.dtd`. There occurs a content model for an element

`<!ELEMENT message ( XML_File_ID, heading, category, sport, Title, Line_Time, ( Notes*, Game+)*, time_stamp )>`

and the ambiguous  sub expression `( Notes*, Game+)*` got blown up during the validation process. By the way, I guess ` ( Notes*, Game)*` is intended, when unpickling the XML. It surprised me, that this error did show up after so many years. Maybe the reason is the ambiguity within the DTD. Most DTDs seem to be deterministic.

However, the validation now is done a bit more clever and it works for all the examples in the test suite,
it now runs in acceptable time. By the way, not all documents there are valid.

The new version ` hxt-9.3.1.11` is uploaded to hackage.

**Comment by orlitzky** [comment]
Thank you for this, the issue I originally reported is fixed.

Regarding the invalid test cases:

My XML source is sending me worse garbage than I originally realized. I'm already generating the DTDs myself, but sometimes they send two completely different document types claiming the same DTD. I'd like to be able to tell the two cases apart. Did I miss something when I generated the DTD, or is this some crazy wrong document that I want nothing to do with? To catch these I think I'll have to leave validation disabled (rather than parse the doc twice) -- that way I can look at the resulting tree before validating it (because it would definitely fail validation).

Thanks again.
