### ISSUE TITLE
No support for interleave pattern

### ISSUE THREAD

**Issue by svenpanne** [UweSchmidt/hxt#37]
AFAICT, hxt has no support for the [interleave pattern](http://relaxng.org/spec-20011203.html#IDA2Z0R).  More concretely, I have no clue how to write an (un-)pickler involving this feature. My example again is the [OpenGL registry RelaxNG schema](https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/registry.rnc), which has `enums` and `commands` elements with an interleave pattern.

How can I (un-)pickle such elements? Can I somehow emulate this using the hxt(-relaxng) API?

**Comment by UweSchmidt** [comment]
(un-)pickling is independent from validation (whether DTD or RelaxNG does not matter). Pickling depends heavily on the Haskell datatype, you have to know the Haskel target. There are indeed only some simple pickers (parser combinators), e.g. xpOption, xpList, but there's no interleave pickler, nor is there a built in pickler for arbitrary sum datatypes.

The automatic transformation of e.g. a RelaxNG schema into a corresponding native Haskell datatype
and the automatic derivation of picklers is an interesting R&D project, but it's really a project, not a task for a weekend.
