### ISSUE TITLE
Broken Haddock syntax in hxt-9.3.1.11

### ISSUE THREAD

**Issue by peti** [UweSchmidt/hxt#38]
Haddock from GHC 7.8.4 fails, saying:

    src/Text/XML/HXT/DTDValidation/RE.hs:197:75:
        parse error on input ‘-- | is right assoc’

The complete build log is at http://hydra.cryp.to/build/522142/nixlog/2/raw.

**Comment by UweSchmidt** [comment]
Fixed and uploaded to hackage: hxt-9.3.1.12!

Thanks for the report
