### ISSUE TITLE
install-plan failures in `hxt`

### ISSUE THREAD

**Issue by hvr** [UweSchmidt/hxt#40]
I recently generated build-report for the `hxt` package, and it doesn't look too good:

https://ghc.haskell.org/~hvr/buildreports/hxt.html

Effectively the only major version of `hxt` that is curently buildable is `9.3.*`, all previous ones have "install-plan-rotted" as it seems.

If you want, I can look into fixing up the cabal meta-data (in most cases it seems it's just a missing upper bound on e.g. `network` that caused problems) on Hackage to turn the red-cells in that build-report-matrix into green ones...

**Comment by UweSchmidt** [comment]
If you use network >= 2.6 as with ghc-7.10, please turn on the flag `network-uri`,
install with `cabal install --flags=network-uri`, else you run into cabal hell.

**Comment by UweSchmidt** [comment]
Forget about the last comment, the latest hxt-9.3.1.15 version on hackage selects with ghc-7.10 the network-uri-2.6 automatically, so a simple `cabal install` should work.

**Comment by hvr** [comment]
@UweSchmidt The problem is not the major version 9.3.* but rather *every* other major version as you can see from the build-report. The cabal meta-data on Hackage is broken/incorrect but it can be fixed. The question if you want me to fix it, or leave it broken and cause problems for down the dependency chain for every other package depending on older versions of `hxt`...

**Comment by hvr** [comment]
To give a concrete example, here's what happen with GHC 7.8.4:

```
$ cabal install 'hxt == 9.2.*' --dry
Resolving dependencies...
In order, the following would be installed (use -v for more details):
HUnit-1.2.5.2
hxt-charproperties-9.2.0.0
hxt-unicode-9.0.2.2
network-2.6.0.2
text-1.2.0.4
transformers-0.4.2.0
mtl-2.2.1
parsec-3.1.8
hxt-regex-xmlschema-9.2.0
hxt-9.2.2 (latest: 9.3.1.13)
```

```
$ cabal install 'hxt == 9.2.*' -j
Resolving dependencies...
Notice: installing into a sandbox located at /tmp/sb/.cabal-sandbox
Configuring HUnit-1.2.5.2...
Configuring hxt-charproperties-9.2.0.0...
Configuring network-2.6.0.2...
Configuring text-1.2.0.4...
Configuring transformers-0.4.2.0...
Building hxt-charproperties-9.2.0.0...
Building HUnit-1.2.5.2...
Building transformers-0.4.2.0...
Building text-1.2.0.4...
Installed HUnit-1.2.5.2
Building network-2.6.0.2...
Installed hxt-charproperties-9.2.0.0
Configuring hxt-unicode-9.0.2.2...
Installed transformers-0.4.2.0
Configuring mtl-2.2.1...
Building hxt-unicode-9.0.2.2...
Building mtl-2.2.1...
Installed network-2.6.0.2
Installed hxt-unicode-9.0.2.2
Installed mtl-2.2.1
Installed text-1.2.0.4
Configuring parsec-3.1.8...
Building parsec-3.1.8...
Installed parsec-3.1.8
Configuring hxt-regex-xmlschema-9.2.0...
Building hxt-regex-xmlschema-9.2.0...
Installed hxt-regex-xmlschema-9.2.0
Configuring hxt-9.2.2...
Building hxt-9.2.2...
Failed to install hxt-9.2.2
Build log ( /tmp/sb/.cabal-sandbox/logs/hxt-9.2.2.log ):
Configuring hxt-9.2.2...
Building hxt-9.2.2...
Preprocessing library hxt-9.2.2...

src/Text/XML/HXT/Arrow/XmlState/URIHandling.hs:36:8:
    Could not find module ‘Network.URI’
    Perhaps you meant Network.BSD (from network-2.6.0.2)
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
hxt-9.2.2 failed during the building phase. The exception was:
ExitFailure 1
```

But this can be fixed by patching the .cabal file on Hackage. And it's a service provided by the [Haskell Trustees](https://github.com/haskell-infra/hackage-trustees) or you can do it yourself (but you'll have to patch/edit several .cabal files due to the way the Cabal solver backtracks).
