### ISSUE TITLE
Processing of specific children is slow

### ISSUE THREAD

**Issue by mrkkrp** [UweSchmidt/hxt#49]
Hello. I'm using the following technique to transform children that have
particular features:

``` haskell
(/>/) :: ArrowXml a => String -> a XmlTree XmlTree -> a XmlTree XmlTree
name />/ action = processChildren $ action `when` (isElem >>> hasName name)
```

As you can see this applies `action` to all children that has name
`name`. Example of usage:

``` haskell
something = "tracklist" />/ inList "track" ("obj" />/ procTrack m)
```

where `procTrack` does some actual processing and `inList` maybe defined
using the same technique:

``` haskell
inList :: ArrowXml a => String -> a XmlTree XmlTree -> a XmlTree XmlTree
inList name action = processChildren $ action `when` isList name
```

etc.

Now, I've noticed that this is not very efficient for large XML documents,
and my only question is whether my approach idiomatic and correct in general
and the slowness of the processing is natural consequence of document size.

I've searched documentation of HXT, but couldn't find primitive that does
something similar to my `(/>/)`, although I'm still thinking it should
exist, because from my point of view this is extremely useful.

Can I improve my code somehow or it's how it should be coded with HXT?

**Comment by UweSchmidt** [comment]
for processing all nodes you should use the processTopDown- or processBottomUp functions,
have a look at "http://hayoo.fh-wedel.de/?query=hxt+processTopDown" . The pattern is

```haskell
processTopDown (action `when` predicate)
```
