### ISSUE TITLE
Text.XML.HXT.Parser.XmlTokenParser is missing some predefinedXMLEntities 

### ISSUE THREAD

**Issue by ralphtq** [UweSchmidt/hxt#50]
Would like support for &amp;nbsp; and &amp;copy; (maybe others) in 

    predefinedXmlEntities   :: [(String, Int)]
    predefinedXmlEntities
        = [ ("lt",   60)
          , ("gt",   62)
          , ("amp",  38)
          , ("apos", 39)
          , ("quot", 34)
          ]

I can send a new version of predefines if requested.

**Comment by UweSchmidt** [comment]
&nbsp; and &copy; are not predefined XML entity refs. These are defined in HTML.
In HXT you can find theses with "http://hayoo.fh-wedel.de/?query=hxt+xhtmlent"
