### ISSUE TITLE
xpChoice for pickling

### ISSUE THREAD

**Issue by sheganinans** [UweSchmidt/hxt#51]
Hello, I don't know if this is exactly the right place to ask this, but I'll give it a shot.

I am trying to write an XmlPickler instance for a rather peculiar xml type. It goes a little something like this:

```haskell
data Expr = Expr
 { expr :: List
 } deriving (Show, Eq)

data List
 = StrList { str :: [String] }
 | IntList { unIn :: [Int] }
 deriving (Show, Eq)

instance XmlPickler Expr where
 xpickle = xpWrap (Expr,expr) . xpElem "expr" $ xpickle

instance XmlPickler List where
 xpickle = xpElem "list" $ xpAlt tag ps where
  tag (StrList _) = 0
  tag (IntList _) = 1
  ps =
   [ xpWrap (StrList,str) . xpList $ xpElem "str" xpText
   , xpWrap (IntList,unIn) . xpList $ xpElem "int" xpInt
   ]
```

Now I want to be able to have an xml file like this:

```xml
<expr>
 <list>
  <str>"a"</str>
  <str>"b"</str>
  <str>"c"</str>
 </list>
 <list>
  <int>1</int>
  <int>2</int>
  <int>3</int>
 </list>
</expr>
```

However I get an error like:

```text
fatal error: document unpickling failed
xpCheckEmptyContents: unprocessed XML content detected
context:    element "list"
contents:   <int>1</int><int>2</int><int>3</int>
```

Basically I want the parser to backtrack on failure of the str instance and to then try the int instance.

**Comment by UweSchmidt** [comment]
your expr-element has a content consisting of 2 list-elements. That will never fit into the Haskell type expr.

**Comment by sheganinans** [comment]
Sure, I just used expr beacause in my full example it is more similar to Haskell's expr. But that doesn't matter, I just renamed it to "bag", since it doesnt matter what the name is, what I have is an XML file that has this bag of lists that may be different types. I was hoping that HXT would provide facilities backtracking on failure, so that if parsing for the str instance failed, it would try the next instance, in this case int. Is that not possible with HXT?

**Comment by UweSchmidt** [comment]
The sum type is your list type, not the element type, the list element must be renamed ore changed, e.g.
as <strlist> and <intlist>. Don't build parsers with backtracking, except for natural languages. All Haskell datatypes can be convertet very easily into XML, that can be parsed straight forward and therefore efficiently.
