### ISSUE TITLE
404 website

### ISSUE THREAD

**Issue by ennioVisco** [UweSchmidt/hxt#77]
Hi,
apparently the [official home](https://www.fh-wedel.de/~si/HXmlToolbox/index.html) page of the project, which is referred also in the official [Haskell Wiki](https://wiki.haskell.org/HXT) is broken.

Is there a new URL or it just got deleted forever?

**Comment by UweSchmidt** [comment]
oh yes, that homepage has been deleted, to git repo
https://github.com/UweSchmidt/hxt
is the appropriate URL

Uwe
