### ISSUE TITLE
passing parameters

### ISSUE THREAD

**Issue by arademaker** [UweSchmidt/hxt#92]
Suppose that I want to pass parameters for getTeams in

https://wiki.haskell.org/HXT/Practical/Simple2

For instance, a typical situation would be when we want to collect data from inner tags using information from outer tags. How can we do that?

**Comment by UweSchmidt** [comment]
Write a function (an arrow) for the outer element,
write a  2. function for the inner tag with a extra parameter

In the 1. function collect info about the outer element,
and pass this info in the extra param to the function for the inner tag

Cheers,

Uwe

**Comment by arademaker** [comment]
The question is precisely about how such a function should be defined! 

```haskell
getSentence = atTag "s" >>>
  proc x -> do
    i   <- getAttrValue "id" -< x
    ts  <- listA getTerminal    <<< atTag "terminals"    -< x
    nts <- listA getNonTerminal <<< atTag "nonterminals" -< x
    wts <- listA getWordTag     <<< atTag "wordtags"     -< x
    frm <- listA getFrame       <<< atTag "frames"       -< x
    let tid = parseSID i in
      returnA -< Sentence { copy = fst tid, sid = snd tid, terminals = ts, nonterminals = nts,
                            wordTags = wts, frames = frm }

...

getTerminal = atTag "t" >>> 
  proc x -> do
    tid <- getAttrValue "id"    -< x    
    lem <- getAttrValue "lemma" -< x
    wor <- getAttrValue "word"  -< x
    mor <- getAttrValue "morph" -< x
    pos <- getAttrValue "pos"   -< x
    returnA -< Terminal { lemma = lem, form = wor, feats = mor , pos = pos, tid = tid }
```

The `i` contains the value that I would like to pass to `getTerminal`. The `getTerminal` would use that extra parameter to properly instantiate the Terminal data instance. 

sorry if the questions is silly, but I would appreciate any more concrete direction.
